### ISSUE TITLE
Break down existing Jupyter notebook into logical steps 

### ISSUE THREAD

**Issue by jt14den** [uc-love-data-week/intermediate-apis#1]

**Comment by jt14den** [comment]
taking apart and building up `get_individual_search_output` in https://github.com/uc-love-data-week/intermediate-apis/blob/main/Figshare.ipynb

**Comment by michaelbaluja** [comment]
Want to work through Zenodo notebook https://github.com/uc-love-data-week/intermediate-apis/blob/main/Zenodo.ipynb since the API is less troublesome than Figshare.

**Comment by kekoziar** [comment]
> Want to work through Zenodo notebook https://github.com/uc-love-data-week/intermediate-apis/blob/main/Zenodo.ipynb since the API is less troublesome than Figshare.

lesson using Zenodo currently on https://github.com/uc-love-data-week/intermediate-apis/blob/main/zenodo_lesson.ipynb

**Comment by jt14den** [comment]
> > Want to work through Zenodo notebook https://github.com/uc-love-data-week/intermediate-apis/blob/main/Zenodo.ipynb since the API is less troublesome than Figshare.
> 
> lesson using Zenodo currently on https://github.com/uc-love-data-week/intermediate-apis/blob/main/zenodo_lesson.ipynb

We can walk thru @kekoziar's Zenodo notebook @michaelbaluja @jmjamison

**Comment by jt14den** [comment]
I still haven't walked thru the notebook, but will over next week.
